# Generated by Django 4.0.6 on 2022-07-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_rename_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Orer Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order completed', 'Order completed'), ('Order Canceled', 'Order Canceled')], max_length=50),
        ),
    ]
